### ISSUE TITLE
I have not configured it right? does not look like I expected?

### ISSUE THREAD

**Issue by westmj** [kraih/vscode-mojo#3]
Using version 1.9.0 on vscode on my chromebook running crouton extension to get bionic with lxde, and with the file (app) login (or renamed login.pl or login.ep, or here attached as login.txt for permission to upload), the highlighting does not look like the example I see here as my_app.pl, where there is highlighting above and below the __DATA__ line.... as if for perl above, and html below....

What am I doing wrong? Hard to make things idiot proof when idiots are so darn clever... do I need to turn off some other extension that is taking priority?

Thank you.
 
![vscode02](https://user-images.githubusercontent.com/13561876/107767223-462e5f00-6cfa-11eb-9419-5fb84dd15a34.png)
![vscode01](https://user-images.githubusercontent.com/13561876/107767246-50e8f400-6cfa-11eb-81a5-3aa7b269bc4b.png)

[login.txt](https://github.com/kraih/vscode-mojo/files/5971703/login.txt)

**Comment by kraih** [comment]
You need `Perl (Mojolicious)`.

**Comment by westmj** [comment]
I may very well.  I sure wish I could figure out what those 4 words mean I should do. Because I am not coming up with anything in vscode in my settings or extensions. sigh.... topic closed...

**Comment by kraih** [comment]
The `Mojolicious` syntax is only for templates, `Perl (Mojolicious)` is for mixed files (it's an extension of the `Perl` syntax).

**Comment by westmj** [comment]
Thanks!  So I will look into how to choose the syntax, and post that for other local users.  ---

**Comment by westmj** [comment]
So, in my vscode, look to the bottom right of the panel, about 3 icons in, there is the text denoting the syntax in use, it may be something like Mojolicious or Perl.  Click on that, then scroll down to pick Perl (Mojolicious).  Ta Dah!   Thanks for the hints.
