### ISSUE TITLE
[Feature Request] new lint rule to require a comment #. at end each python block.

### ISSUE THREAD

**Issue by EdSaleh** [kraih/vscode-mojo#5]
Create a new rule to require that each block must end with # or #. 
This would work as a curly braces blocks found in C style languages.
Also, this could also be used to reformat python code by code editor to fix any indentation issues.

Example:

```python
import string
def atbash(sequence: str) -> str:
    """
    Example
    """
    output = ""
    for i in sequence:
        extract = ord(i)
        if 65 <= extract <= 90:
            output += chr(155 - extract)
        #.
        elif 97 <= extract <= 122:
            output += chr(219 - extract)
        #.
        else:
            output += i
        #.
    #.
    return output
#.
```

**Comment by jberger** [comment]
I think you're looking for some other repo. This is syntax highlighting for a perl-based web framework. Nothing to do with python
